import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import nextPackage from "package.json";

export default function Home({}) {

  const [users, setUsers] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch('https://trenova-training-participants-data-api-3ccr.vercel.app/api/auth/signup');
        const data = await response.json();
        setUsers(data.users);
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      {users.map((user) => (
        <div key={user._id}>
          {/* Render user details */}
          <p>{user.participantName}</p>
          <p>{user.schoolName}</p>
          {/* Render other user properties */}
        </div>
      ))}

      </main>
    </div>
  );
}
