import Head from "next/head";
import React, { useState } from "react";
import axios, { AxiosError } from 'axios'
import styles from "../styles/Home.module.css";
import nextPackage from "package.json";


export default function Home({}) {

  const [data, setData] = useState({
    participantName : "",
  schoolName : "",
  address : "",
  phoneNumber : "",
  email : "",

})




// const handleSignup = async (event: React.FormEvent<HTMLFormElement>) => {
//   event.preventDefault()


//       try {

//           const axiosInstance = axios.create({
//             baseURL: 'https://trenova-training-participants-data-api-3ccr.vercel.app/',
//             withCredentials: true,
//           });

//           const apiRes = await axiosInstance.post('/api/auth/signup', data);

//           if (apiRes?.data?.success) {
            

//               alert('data was sent')

//           }
//       } catch (error: unknown) {
//           if (error instanceof AxiosError) {
//               const errorMsg = error.response?.data?.error
          
//               console.log(error.response?.data?.error)
//           }
//       }

     
  
// }





// const handleInputChange = (event: React.ChangeEvent<HTMLInputElement   | HTMLSelectElement>) => {

//   setData({ ...data, [event.target.name]: event.target.value })
// }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      <form action=""   >


          
                <div className="content    flex flex-col items-center">
                               <div className="header mb-[8%] w-full flex justify-center items-center text-center  text-[2.5vw]  portrait:text-[7vw]  portrait:sm:text-[5vw]">
  <span>MAKE REVIEWS AND DISCOVER COMPANIES</span>
</div>    




<div className="input-div flex flex-col justify-between items-center w-[70%] portrait:w-[90%]   portrait:sm:w-[90%] portrait:sm:text-[3.5vw] mb-[3vw] portrait:mb-[7vw]">
<label htmlFor='companyName' className='self-start mb-2'>PARTICIPANT NAME</label>
<input title='companyName' required type="text"    value={data.participantName}    name="participantName" id="" className='border-none outline-none rounded h-[3vw] portrait:h-[10vw] w-[100%] px-2 portrait:sm:px-[2vw]'/>

</div>

<div className="input-div flex flex-col justify-between items-center w-[70%] portrait:w-[90%]   portrait:sm:w-[90%] portrait:sm:text-[3.5vw] mb-[3vw] portrait:mb-[7vw]">
<label htmlFor='firstName'  className='self-start mb-2'>SCHOOL NAME</label>
<input  title='firstName' required type="text"     value={data.schoolName}  name="schoolName" id="" className='border-none outline-none rounded h-[3vw] portrait:h-[10vw] w-[100%] px-2 portrait:sm:px-[2vw]'/>

</div>
<div className="input-div flex flex-col justify-between items-center w-[70%] portrait:w-[90%]   portrait:sm:w-[90%] portrait:sm:text-[3.5vw] mb-[3vw] portrait:mb-[7vw]">
<label htmlFor='lastName' className='self-start mb-2'>ADDRESS</label>
<input  title='lastName' required type="text"     value={data.address}   name="address" id="" className='border-none outline-none rounded h-[3vw] portrait:h-[10vw] w-[100%] px-2 portrait:sm:px-[2vw]'/>

</div>
<div className="input-div flex flex-col justify-between items-center w-[70%] portrait:w-[90%]   portrait:sm:w-[90%] portrait:sm:text-[3.5vw] mb-[3vw] portrait:mb-[7vw]">
<label className='self-start mb-2'>PHONE NUMBER</label>
<input title='jobTitle' required type="text"    value={data.phoneNumber}  name="phoneNumber" id="" className='border-none outline-none rounded h-[3vw] portrait:h-[10vw] w-[100%] px-2 portrait:sm:px-[2vw]'/>

</div>



<div className="input-div flex flex-col justify-between items-center w-[70%] portrait:w-[90%]   portrait:sm:w-[90%] portrait:sm:text-[3.5vw] mb-[3vw] portrait:mb-[7vw]">
<label htmlFor='email' className='self-start mb-2'>EMAIL</label>
<input title='email' required  type="email"   value={data.email}  name="email" id="" className='border-none outline-none rounded h-[3vw] portrait:h-[10vw] w-[100%] px-2 portrait:sm:px-[2vw]'/>

</div>


<button  title={"Sign up"} type="submit"  className='w-full'>
<div className="w-full  BTN text-[1.5vw] portrait:text-[4.4vw]  portrait:sm:text-[4vw] flex justify-center items-center mb-4">
     <span className='w-[60%] h-[4vw]   portrait:h-[10vw] portrait:w-[70%] portrait:sm:w-[60%]  transition-all ease-in duration-[0.5s] bg-lightgreen hover:bg-blue hover:text-armygreen   px-[2vw] py-[0.5vw] text-grey rounded cursor-pointer flex justify-center items-center'> <span>REGISTER USER</span> </span>
</div>
</button>





                </div>
                </form>

      </main>
    </div>
  );
}
